export const HOME_PAGE = "HOME_PAGE";
export const FOLLOWED_USERS_POSTS_PAGE = "FOLLOWED_USERS_POSTS_PAGE";
export const MOST_KARMA_POSTS_PAGE = "MOST_KARMA_POSTS_PAGE";
export const MY_NETWORK_PAGE = "MY_NETWORK_PAGE";
export const CONNECTIONS_PAGE = "CONNECTIONS_PAGE";
export const PEOPLE_I_FOLLOW_PAGE = "PEOPLE_I_FOLLOW_PAGE";
export const HELPED_POSTS_PAGE = "HELPED_POSTS_PAGE";
export const USER_POSTS_PAGE = "USER_POSTS_PAGE";
