export const HOME_PAGE = "HOME_PAGE";
export const FOLLOWED_USERS_POSTS_PAGE = "FOLLOWED_USERS_POSTS_PAGE";
export const MOST_KARMA_POSTS_PAGE = "MOST_KARMA_POSTS_PAGE";
export const MY_NETWORK_PAGE = "MY_NETWORK_PAGE";
export const CONNECTIONS_PAGE = "CONNECTIONS_PAGE";
export const PEOPLE_I_FOLLOW_PAGE = "PEOPLE_I_FOLLOW_PAGE";
export const MY_POSTS_PAGE = "MY_POSTS_PAGE";
export const CONTRIBUTED = "CONTRIBUTED";
export const ACTIVE_CONTRIBUTED = "ACTIVE_CONTRIBUTED";
export const CLOSED_CONTRIBUTED = "CLOSED_CONTRIBUTED";
export const HELP_PAGE = "HELP_PAGE";
export const SEARCH_POSTS_PAGE = "SEARCH_POSTS_PAGE";
export const SEARCH_USERS_PAGE = "SEARCH_USERS_PAGE";
export const PROFILE_PAGE = "PROFILE_PAGE";
export const ACTIVE_POSTS_PROFILE_PAGE = "ACTIVE_POSTS_PROFILE_PAGE";
export const CLOSED_POSTS_PROFILE_PAGE = "CLOSED_POSTS_PROFILE_PAGE";
export const USER_CONTRIBUTED = "USER_CONTRIBUTED";
export const POST_PAGE = "POST_PAGE";
export const DONATION_PAGE = "DONATION_PAGE";
export const REVIEWS_PAGE = "REVIEWS_PAGE";
export const PROFILE_REVIEWS_PAGE = "PROFILE_REVIEWS_PAGE";
export const REQUESTS_PAGE = "REQUESTS_PAGE";
export const NOTIFICATIONS_PAGE = "NOTIFICATIONS_PAGE";

// SETTINGS PAGES
export const SETTINGS_PAGE = "SETTINGS_PAGE";
