// Portals
export const FETCH_PORTAL = "FETCH_PORTAL";
export const FETCH_PORTAL_SUCCESS = "FETCH_PORTAL_SUCCESS";
export const FETCH_PORTAL_FAIL = "FETCH_PORTAL_FAIL";
export const UPDATE_PORTAL = "UPDATE_PORTAL";
export const UPDATE_PORTAL_SUCCESS = "UPDATE_PORTAL_SUCCESS";
export const UPDATE_PORTAL_FAIL = "UPDATE_PORTAL_FAIL";
export const IS_NAME_AVAILABLE = "IS_NAME_AVAILABLE";
export const IS_NAME_AVAILABLE_SUCCESS = "IS_NAME_AVAILABLE_SUCCESS";
export const IS_NAME_AVAILABLE_FAIL = "IS_NAME_AVAILABLE_FAIL";
export const RESET_NAME_AVAILABLE = "RESET_NAME_AVAILABLE";
export const IS_URL_AVAILABLE = "IS_URL_AVAILABLE";
export const IS_URL_AVAILABLE_SUCCESS = "IS_URL_AVAILABLE_SUCCESS";
export const IS_URL_AVAILABLE_FAIL = "IS_URL_AVAILABLE_FAIL";
export const RESET_URL_AVAILABLE = "RESET_URL_AVAILABLE";
export const ADD_BILLING_INFORMATION = "ADD_BILLING_INFORMATION";
export const ADD_BILLING_INFORMATION_SUCCESS =
  "ADD_BILLING_INFORMATION_SUCCESS";
export const ADD_BILLING_INFORMATION_FAIL = "ADD_BILLING_INFORMATION_FAIL";
export const CHANGE_PAYMENT_METHOD_PORTAL = "CHANGE_PAYMENT_METHOD_PORTAL";
export const CHANGE_PAYMENT_METHOD_PORTAL_SUCCESS =
  "CHANGE_PAYMENT_METHOD_PORTAL_SUCCESS";
export const CHANGE_PAYMENT_METHOD_PORTAL_FAIL =
  "CHANGE_PAYMENT_METHOD_PORTAL_FAIL";
export const CHANGE_PLAN = "CHANGE_PLAN";
export const CHANGE_PLAN_SUCCESS = "CHANGE_PLAN_SUCCESS";
export const CHANGE_PLAN_FAIL = "CHANGE_PLAN_FAIL";
export const CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION";
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS";
export const CANCEL_SUBSCRIPTION_FAIL = "CANCEL_SUBSCRIPTION_FAIL";
export const REACTIVATE_SUBSCRIPTION = "REACTIVATE_SUBSCRIPTION";
export const REACTIVATE_SUBSCRIPTION_SUCCESS =
  "REACTIVATE_SUBSCRIPTION_SUCCESS";
export const REACTIVATE_SUBSCRIPTION_FAIL = "REACTIVATE_SUBSCRIPTION_FAIL";

// Dispatch control reducers
export const INITIAL_DATA_FETCHED = "INITIAL_DATA_FETCHED";
export const RESET_DATA_FETCHED = "RESET_DATA_FETCHED";

// Alerts
export const CREATE_ALERT = "CREATE_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Auth
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_COMMUNITY_FILTER = "CHANGE_COMMUNITY_FILTER";
export const CHANGE_STATUS_FILTER = "CHANGE_STATUS_FILTER";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAIL = "CHANGE_EMAIL_FAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const RESET_CHANGE_PASSWORD_ERRORS = "RESET_CHANGE_PASSWORD_ERRORS";
export const STRIPE_CONNECTED = "STRIPE_CONNECTED";
export const STRIPE_CONNECTED_SUCCESS = "STRIPE_CONNECTED_SUCCESS";
export const STRIPE_CONNECTED_FAIL = "STRIPE_CONNECTED_FAIL";
export const SET_STRIPE_CUSTOMER_DATA = "SET_STRIPE_CUSTOMER_DATA";
export const RESET_AUTH_ERRORS = "RESET_AUTH_ERRORS";
export const TOOGLE_VIEWS = "TOOGLE_VIEWS";
export const IS_EMAIL_AVAILABLE = "IS_EMAIL_AVAILABLE";
export const IS_EMAIL_AVAILABLE_SUCCESS = "IS_EMAIL_AVAILABLE_SUCCESS";
export const IS_EMAIL_AVAILABLE_FAIL = "IS_EMAIL_AVAILABLE_FAIL";
export const RESET_EMAIL_AVAILABLE = "RESET_EMAIL_AVAILABLE";
export const IS_USERNAME_AVAILABLE = "IS_USERNAME_AVAILABLE";
export const IS_USERNAME_AVAILABLE_SUCCESS = "IS_USERNAME_AVAILABLE_SUCCESS";
export const IS_USERNAME_AVAILABLE_FAIL = "IS_USERNAME_AVAILABLE_FAIL";
export const RESET_USERNAME_AVAILABLE = "RESET_USERNAME_AVAILABLE";
export const IS_COUPON_AVAILABLE = "IS_COUPON_AVAILABLE";
export const IS_COUPON_AVAILABLE_SUCCESS = "IS_COUPON_AVAILABLE_SUCCESS";
export const IS_COUPON_AVAILABLE_FAIL = "IS_COUPON_AVAILABLE_FAIL";
export const RESET_COUPON_AVAILABLE = "RESET_COUPON_AVAILABLE";
export const SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL";
export const SEND_VERIFICATION_EMAIL_SUCCESS =
  "SEND_VERIFICATION_EMAIL_SUCCESS";
export const SEND_VERIFICATION_EMAIL_FAIL = "SEND_VERIFICATION_EMAIL_FAIL";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";
export const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
export const VERIFY_ACCOUNT_FAIL = "VERIFY_ACCOUNT_FAIL";
export const VALIDATE_CHANGE_EMAIL = "VALIDATE_CHANGE_EMAIL";
export const VALIDATE_CHANGE_EMAIL_SUCCESS = "VALIDATE_CHANGE_EMAIL_SUCCESS";
export const VALIDATE_CHANGE_EMAIL_FAIL = "VALIDATE_CHANGE_EMAIL_FAIL";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const INVITE_USER = "INVITE_USER";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const INVITE_USER_FAIL = "INVITE_USER_FAIL";
export const RESET_INVITE_USER = "RESET_INVITE_USER";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const SET_PENDING_NOTIFICATIONS = "SET_PENDING_NOTIFICATIONS";
export const SET_PENDING_MESSAGES = "SET_PENDING_MESSAGES";
export const UNSET_PENDING_NOTIFICATIONS = "UNSET_PENDING_NOTIFICATIONS";
export const UNSET_PENDING_MESSAGES = "UNSET_PENDING_MESSAGES";
export const SET_ALL_NOTIFICATIONS_READ = "SET_ALL_NOTIFICATIONS_READ";
export const SET_ALL_NOTIFICATIONS_READ_SUCCESS =
  "SET_ALL_NOTIFICATIONS_READ_SUCCESS";
export const SET_ALL_NOTIFICATIONS_READ_FAIL =
  "SET_ALL_NOTIFICATIONS_READ_FAIL";
export const STRIPE_CONNECT = "STRIPE_CONNECT";
export const STRIPE_CONNECT_SUCCESS = "STRIPE_CONNECT_SUCCESS";
export const STRIPE_CONNECT_FAIL = "STRIPE_CONNECT_FAIL";
export const CHANGE_PAYMENT_METHOD = "CHANGE_PAYMENT_METHOD";
export const CHANGE_PAYMENT_METHOD_SUCCESS = "CHANGE_PAYMENT_METHOD_SUCCESS";
export const CHANGE_PAYMENT_METHOD_FAIL = "CHANGE_PAYMENT_METHOD_FAIL";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";

export const BECOME_A_SELLER = "BECOME_A_SELLER";
export const BECOME_A_SELLER_SUCCESS = "BECOME_A_SELLER_SUCCESS";
export const BECOME_A_SELLER_FAIL = "BECOME_A_SELLER_FAIL";
export const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export const ADD_PAYMENT_METHOD_SUCCESS = "ADD_PAYMENT_METHOD_SUCCESS";
export const ADD_PAYMENT_METHOD_FAIL = "ADD_PAYMENT_METHOD_FAIL";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const REMOVE_ACCOUNT_SUCCESS = "REMOVE_ACCOUNT_SUCCESS";
export const REMOVE_ACCOUNT_FAIL = "REMOVE_ACCOUNT_FAIL";
export const LEAVE_FEEDBACK = "LEAVE_FEEDBACK";
export const LEAVE_FEEDBACK_SUCCESS = "LEAVE_FEEDBACK_SUCCESS";
export const LEAVE_FEEDBACK_FAIL = "LEAVE_FEEDBACK_FAIL";
export const UPDATE_GEOLOCATION = "UPDATE_GEOLOCATION";
export const UPDATE_GEOLOCATION_SUCCESS = "UPDATE_GEOLOCATION_SUCCESS";
export const UPDATE_GEOLOCATION_FAIL = "UPDATE_GEOLOCATION_FAIL";
export const SET_PAYMENT_METHODS = "SET_PAYMENT_METHODS";

// Donations
export const FETCH_DONATIONS = "FETCH_DONATIONS";
export const FETCH_DONATIONS_SUCCESS = "FETCH_DONATIONS_SUCCESS";
export const FETCH_DONATIONS_FAIL = "FETCH_DONATIONS_FAIL";
export const FETCH_MORE_DONATIONS = "FETCH_MORE_DONATIONS";
export const FETCH_MORE_DONATIONS_SUCCESS = "FETCH_MORE_DONATIONS_SUCCESS";
export const FETCH_MORE_DONATIONS_FAIL = "FETCH_MORE_DONATIONS_FAIL";

// User statistics
export const ADD_KARMA_AMOUNT = "ADD_KARMA_AMOUNT";
export const SUBSTRACT_KARMA_AMOUNT = "SUBSTRACT_KARMA_AMOUNT";

// Network
export const ADD_INVITATION = "ADD_INVITATION";
export const SUBSTRACT_INVITATION = "SUBSTRACT_INVITATION";
export const ADD_CONNECTION = "ADD_CONNECTION";
export const SUBSTRACT_CONNECTION = "SUBSTRACT_CONNECTION";
export const ADD_FOLLOW = "ADD_FOLLOW";
export const SUBSTRACT_FOLLOW = "SUBSTRACT_FOLLOW";

// Posts
export const ADD_POST_COUNT = "ADD_POST_COUNT";
export const SUBSTRACT_POST_COUNT = "SUBSTRACT_POST_COUNT";
export const ADD_CREATED_POST_COUNT = "ADD_CREATED_POST_COUNT";
export const SUBSTRACT_CREATED_POST_COUNT = "SUBSTRACT_CREATED_POST_COUNT";
export const ADD_CREATED_ACTIVE_POST_COUNT = "ADD_CREATED_ACTIVE_POST_COUNT";
export const SUBSTRACT_CREATED_ACTIVE_POST_COUNT =
  "SUBSTRACT_CREATED_ACTIVE_POST_COUNT";
export const ADD_CREATED_SOLVED_POST_COUNT = "ADD_CREATED_SOLVED_POST_COUNT";
export const SUBSTRACT_CREATED_SOLVED_POST_COUNT =
  "SUBSTRACT_CREATED_SOLVED_POST_COUNT";

// Invitations
export const FETCH_INVITATIONS = "FETCH_INVITATIONS";
export const FETCH_INVITATIONS_SUCCESS = "FETCH_INVITATIONS_SUCCESS";
export const FETCH_INVITATIONS_FAIL = "FETCH_INVITATIONS_FAIL";
export const ACCEPT_INVITATION = "ACCEPT_INVITATION";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAIL = "ACCEPT_INVITATION_FAIL";
export const IGNORE_INVITATION = "IGNORE_INVITATION";
export const IGNORE_INVITATION_SUCCESS = "IGNORE_INVITATION_SUCCESS";
export const IGNORE_INVITATION_FAIL = "IGNORE_INVITATION_FAIL";

// Connections
export const FETCH_CONNECTIONS = "FETCH_CONNECTIONS";
export const FETCH_CONNECTIONS_SUCCESS = "FETCH_CONNECTIONS_SUCCESS";
export const FETCH_CONNECTIONS_FAIL = "FETCH_CONNECTIONS_FAIL";
export const REMOVE_CONNECTION = "REMOVE_CONNECTION";
export const REMOVE_CONNECTION_SUCCESS = "REMOVE_CONNECTION_SUCCESS";
export const REMOVE_CONNECTION_FAIL = "REMOVE_CONNECTION_FAIL";

// Followed
export const FETCH_FOLLOWING = "FETCH_FOLLOWING";
export const FETCH_FOLLOWING_SUCCESS = "FETCH_FOLLOWING_SUCCESS";
export const FETCH_FOLLOWING_FAIL = "FETCH_FOLLOWING_FAIL";
export const STOP_FOLLOWING = "STOP_FOLLOWING";
export const STOP_FOLLOWING_SUCCESS = "STOP_FOLLOWING_SUCCESS";
export const STOP_FOLLOWING_FAIL = "STOP_FOLLOWING_FAIL";

// Top Karma Users
export const FETCH_TOP_KARMA_USERS = "FETCH_TOP_KARMA_USERS";
export const FETCH_TOP_KARMA_USERS_SUCCESS = "FETCH_TOP_KARMA_USERS_SUCCESS";
export const FETCH_TOP_KARMA_USERS_FAIL = "FETCH_TOP_KARMA_USERS_FAIL";
export const FOLLOW_TOP_KARMA_USER = "FOLLOW_TOP_KARMA_USER";
export const FOLLOW_TOP_KARMA_USER_SUCCESS = "FOLLOW_TOP_KARMA_USER_SUCCESS";
export const FOLLOW_TOP_KARMA_USER_FAIL = "FOLLOW_TOP_KARMA_USER_FAIL";

// User
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const FOLLOW_USER = "FOLLOW_USER";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";
export const STOP_FOLLOWING_USER = "STOP_FOLLOWING_USER";
export const STOP_FOLLOWING_USER_SUCCESS = "STOP_FOLLOWING_USER_SUCCESS";
export const STOP_FOLLOWING_USER_FAIL = "STOP_FOLLOWING_USER_FAIL";
export const CONNECT_USER = "CONNECT_USER";
export const CONNECT_USER_SUCCESS = "CONNECT_USER_SUCCESS";
export const CONNECT_USER_FAIL = "CONNECT_USER_FAIL";
export const ACCEPT_USER_INVITATION = "ACCEPT_USER_INVITATION";
export const ACCEPT_USER_INVITATION_SUCCESS = "ACCEPT_USER_INVITATION_SUCCESS";
export const ACCEPT_USER_INVITATION_FAIL = "ACCEPT_USER_INVITATION_FAIL";
export const REMOVE_USER_CONNECTION = "REMOVE_USER_CONNECTION";
export const REMOVE_USER_CONNECTION_SUCCESS = "REMOVE_USER_CONNECTION_SUCCESS";
export const REMOVE_USER_CONNECTION_FAIL = "REMOVE_USER_CONNECTION_FAIL";
export const DONATE_USER = "DONATE_USER";
export const DONATE_USER_SUCCESS = "DONATE_USER_SUCCESS";
export const DONATE_USER_FAIL = "DONATE_USER_FAIL";

// Users
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const FETCH_MORE_USERS = "FETCH_MORE_USERS";
export const FETCH_MORE_USERS_SUCCESS = "FETCH_MORE_USERS_SUCCESS";
export const FETCH_MORE_USERS_FAIL = "FETCH_MORE_USERS_FAIL";
export const FOLLOW_USER_IN_USERS = "FOLLOW_USER_IN_USERS";
export const FOLLOW_USER_IN_USERS_SUCCESS = "FOLLOW_USER_IN_USERS_SUCCESS";
export const FOLLOW_USER_IN_USERS_FAIL = "FOLLOW_USER_IN_USERS_FAIL";

// Invoices
export const FETCH_INVOICES = "FETCH_INVOICES";
export const FETCH_INVOICES_SUCCESS = "FETCH_INVOICES_SUCCESS";
export const FETCH_INVOICES_FAIL = "FETCH_INVOICES_FAIL";

// PayPal
export const PAYPAL_CONNECT = "PAYPAL_CONNECT";
export const PAYPAL_CONNECT_SUCCESS = "PAYPAL_CONNECT_SUCCESS";
export const PAYPAL_CONNECT_FAIL = "PAYPAL_CONNECT_FAIL";

// Earnings
export const FETCH_EARNINGS = "FETCH_EARNINGS";
export const FETCH_EARNINGS_SUCCESS = "FETCH_EARNINGS_SUCCESS";
export const FETCH_EARNINGS_FAIL = "FETCH_EARNINGS_FAIL";
export const WITHDRAW_FUNDS = "WITHDRAW_FUNDS";
export const WITHDRAW_FUNDS_SUCCESS = "WITHDRAW_FUNDS_SUCCESS";
export const WITHDRAW_FUNDS_FAIL = "WITHDRAW_FUNDS_FAIL";
export const SET_NEW_EARNINGS_TO_USER = "SET_NEW_EARNINGS_TO_USER";

// Contacts
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_FAIL = "FETCH_CONTACTS_FAIL";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
export const SEARCH_CONTACTS_SUCCESS = "SEARCH_CONTACTS_SUCCESS";
export const SEARCH_CONTACTS_FAIL = "SEARCH_CONTACTS_FAIL";
export const FETCH_AVAILABLE_CONTACTS = "FETCH_AVAILABLE_CONTACTS";
export const FETCH_AVAILABLE_CONTACTS_SUCCESS =
  "FETCH_AVAILABLE_CONTACTS_SUCCESS";
export const FETCH_AVAILABLE_CONTACTS_FAIL = "FETCH_AVAILABLE_CONTACTS_FAIL";
export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const REMOVE_CONTACT_SUCCESS = "REMOVE_CONTACT_SUCCESS";
export const REMOVE_CONTACT_FAIL = "REMOVE_CONTACT_FAIL";

// Chats
export const OPEN_CHATS = "OPEN_CHATS";
export const CLOSE_CHATS = "CLOSE_CHATS";
export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";
export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAIL = "FETCH_CHATS_FAIL";
export const SET_SEEN_CHAT = "SET_SEEN_CHAT";
export const NEW_MESSAGE_EVENT = "NEW_MESSAGE_EVENT";
export const CHANGE_LAST_MESSAGE = "CHANGE_LAST_MESSAGE";
export const ADD_CHAT_TO_FEED = "ADD_CHAT_TO_FEED";
export const ADD_CHAT_TO_FEED_SUCCESS = "ADD_CHAT_TO_FEED_SUCCESS";
export const ADD_CHAT_TO_FEED_FAIL = "ADD_CHAT_TO_FEED_FAIL";

// Chat
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const FETCH_CHAT = "FETCH_CHAT";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAIL = "FETCH_CHAT_FAIL";
export const REMOVE_CURRENT_CHAT = "REMOVE_CURRENT_CHAT";
export const RESET_CHAT = "RESET_CHAT";

// Messages
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";
export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAIL = "FETCH_MESSAGE_FAIL";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const FETCH_MORE_MESSAGES = "FETCH_MORE_MESSAGES";
export const FETCH_MORE_MESSAGES_SUCCESS = "FETCH_MORE_MESSAGES_SUCCESS";
export const FETCH_MORE_MESSAGES_FAIL = "FETCH_MORE_MESSAGES_FAIL";
export const RESET_MESSAGES = "RESET_MESSAGES";

// Last notifications
export const FETCH_LAST_NOTIFICATIONS = "FETCH_LAST_NOTIFICATIONS";
export const FETCH_LAST_NOTIFICATIONS_SUCCESS =
  "FETCH_LAST_NOTIFICATIONS_SUCCESS";
export const FETCH_LAST_NOTIFICATIONS_FAIL = "FETCH_LAST_NOTIFICATIONS_FAIL";
export const SET_NOTIFICATION_READ = "SET_NOTIFICATION_READ";
export const SET_NOTIFICATION_READ_SUCCESS = "SET_NOTIFICATION_READ_SUCCESS";
export const SET_NOTIFICATION_READ_FAIL = "SET_NOTIFICATION_READ_FAIL";

// Notifications
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAIL = "FETCH_NOTIFICATIONS_FAIL";
export const FETCH_MORE_NOTIFICATIONS = "FETCH_MORE_NOTIFICATIONS";
export const FETCH_MORE_NOTIFICATIONS_SUCCESS =
  "FETCH_MORE_NOTIFICATIONS_SUCCESS";
export const FETCH_MORE_NOTIFICATIONS_FAIL = "FETCH_MORE_NOTIFICATIONS_FAIL";
export const ADD_NOTIFICATION_TO_FEED = "ADD_NOTIFICATION_TO_FEED";
export const ADD_NOTIFICATION_TO_FEED_SUCCESS =
  "ADD_NOTIFICATION_TO_FEED_SUCCESS";
export const UPDATE_NOTIFICATION_TO_FEED_SUCCESS =
  "UPDATE_NOTIFICATION_TO_FEED_SUCCESS";
export const ADD_NOTIFICATION_TO_FEED_FAIL = "ADD_NOTIFICATION_TO_FEED_FAIL";

// Plans
export const FETCH_PLANS = "FETCH_PLANS";
export const FETCH_PLANS_SUCCESS = "FETCH_PLANS_SUCCESS";
export const FETCH_PLANS_FAIL = "FETCH_PLANS_FAIL";

// Offers
export const SEARCH_BUYERS = "SEARCH_BUYERS";
export const SEARCH_BUYERS_SUCCESS = "SEARCH_BUYERS_SUCCESS";
export const SEARCH_BUYERS_FAIL = "SEARCH_BUYERS_FAIL";
export const CREATE_OFFER = "CREATE_OFFER";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAIL = "CREATE_OFFER_FAIL";
export const FETCH_OFFER = "FETCH_OFFER";
export const FETCH_OFFER_SUCCESS = "FETCH_OFFER_SUCCESS";
export const FETCH_OFFER_FAIL = "FETCH_OFFER_FAIL";
export const ACCEPT_OFFER = "ACCEPT_OFFER";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
export const ACCEPT_OFFER_FAIL = "ACCEPT_OFFER_FAIL";

// Orders
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

// Order
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";
export const FETCH_ORDER_ACTIVITIES = "FETCH_ORDER_ACTIVITIES";
export const FETCH_ORDER_ACTIVITIES_SUCCESS = "FETCH_ORDER_ACTIVITIES_SUCCESS";
export const FETCH_ORDER_ACTIVITIES_FAIL = "FETCH_ORDER_ACTIVITIES_FAIL";
export const DELIVER_ORDER = "DELIVER_ORDER";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAIL = "DELIVER_ORDER_FAIL";
export const CANCELATION_REQUEST = "CANCELATION_REQUEST";
export const CANCELATION_REQUEST_SUCCESS = "CANCELATION_REQUEST_SUCCESS";
export const CANCELATION_REQUEST_FAIL = "CANCELATION_REQUEST_FAIL";
export const CANCEL_CANCELATION_REQUEST = "CANCEL_CANCELATION_REQUEST";
export const CANCEL_CANCELATION_REQUEST_SUCCESS =
  "CANCEL_CANCELATION_REQUEST_SUCCESS";
export const CANCEL_CANCELATION_REQUEST_FAIL =
  "CANCEL_CANCELATION_REQUEST_FAIL";
export const ACCEPT_CANCELATION_REQUEST = "ACCEPT_CANCELATION_REQUEST";
export const ACCEPT_CANCELATION_REQUEST_SUCCESS =
  "ACCEPT_CANCELATION_REQUEST_SUCCESS";
export const ACCEPT_CANCELATION_REQUEST_FAIL =
  "ACCEPT_CANCELATION_REQUEST_FAIL";
export const REVISION_REQUEST = "REVISION_REQUEST";
export const REVISION_REQUEST_SUCCESS = "REVISION_REQUEST_SUCCESS";
export const REVISION_REQUEST_FAIL = "REVISION_REQUEST_FAIL";
export const ACCEPT_DELIVERY = "ACCEPT_DELIVERY";
export const ACCEPT_DELIVERY_SUCCESS = "ACCEPT_DELIVERY_SUCCESS";
export const ACCEPT_DELIVERY_FAIL = "ACCEPT_DELIVERY_FAIL";
export const UNSUBSCRIBE_ORDER = "UNSUBSCRIBE_ORDER";
export const UNSUBSCRIBE_ORDER_SUCCESS = "UNSUBSCRIBE_ORDER_SUCCESS";
export const UNSUBSCRIBE_ORDER_FAIL = "UNSUBSCRIBE_ORDER_FAIL";

// Dashboard Orders
export const FETCH_DASHBOARD_ORDERS = "FETCH_DASHBOARD_ORDERS";
export const FETCH_DASHBOARD_ORDERS_SUCCESS = "FETCH_DASHBOARD_ORDERS_SUCCESS";
export const FETCH_DASHBOARD_ORDERS_FAIL = "FETCH_DASHBOARD_ORDERS_FAIL";

// Last messages
export const FETCH_LAST_MESSAGES = "FETCH_LAST_MESSAGES";
export const FETCH_LAST_MESSAGES_SUCCESS = "FETCH_LAST_MESSAGES_SUCCESS";
export const FETCH_LAST_MESSAGES_FAIL = "FETCH_LAST_MESSAGES_FAIL";

// Activities
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_FAIL = "FETCH_ACTIVITIES_FAIL";

// Posts
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";
export const FETCH_MORE_POSTS = "FETCH_MORE_POSTS";
export const FETCH_MORE_POSTS_SUCCESS = "FETCH_MORE_POSTS_SUCCESS";
export const FETCH_MORE_POSTS_FAIL = "FETCH_MORE_POSTS_FAIL";
export const CREATE_CONTRIBUTE_REQUEST = "CREATE_CONTRIBUTE_REQUEST";
export const CREATE_CONTRIBUTE_REQUEST_SUCCESS =
  "CREATE_CONTRIBUTE_REQUEST_SUCCESS";
export const CREATE_CONTRIBUTE_REQUEST_FAIL = "CREATE_CONTRIBUTE_REQUEST_FAIL";

// Post
export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";
export const CREATE_POST_CONTRIBUTE_REQUEST = "CREATE_POST_CONTRIBUTE_REQUEST";
export const CREATE_POST_CONTRIBUTE_REQUEST_SUCCESS =
  "CREATE_POST_CONTRIBUTE_REQUEST_SUCCESS";
export const CREATE_POST_CONTRIBUTE_REQUEST_FAIL =
  "CREATE_POST_CONTRIBUTE_REQUEST_FAIL";

// Contribute request
export const FETCH_CONTRIBUTE_REQUESTS = "FETCH_CONTRIBUTE_REQUESTS";
export const FETCH_CONTRIBUTE_REQUESTS_SUCCESS =
  "FETCH_CONTRIBUTE_REQUESTS_SUCCESS";
export const FETCH_CONTRIBUTE_REQUESTS_FAIL = "FETCH_CONTRIBUTE_REQUESTS_FAIL";
export const FETCH_MORE_CONTRIBUTE_REQUESTS = "FETCH_MORE_CONTRIBUTE_REQUESTS";
export const FETCH_MORE_CONTRIBUTE_REQUESTS_SUCCESS =
  "FETCH_MORE_CONTRIBUTE_REQUESTS_SUCCESS";
export const FETCH_MORE_CONTRIBUTE_REQUESTS_FAIL =
  "FETCH_MORE_CONTRIBUTE_REQUESTS_FAIL";
export const FETCH_CONTRIBUTE_REQUEST = "FETCH_CONTRIBUTE_REQUEST";
export const FETCH_CONTRIBUTE_REQUEST_SUCCESS =
  "FETCH_CONTRIBUTE_REQUEST_SUCCESS";
export const FETCH_CONTRIBUTE_REQUEST_FAIL = "FETCH_CONTRIBUTE_REQUEST_FAIL";
export const ACCEPT_CONTRIBUTE_REQUEST = "ACCEPT_CONTRIBUTE_REQUEST";
export const ACCEPT_CONTRIBUTE_REQUEST_SUCCESS =
  "ACCEPT_CONTRIBUTE_REQUEST_SUCCESS";
export const ACCEPT_CONTRIBUTE_REQUEST_FAIL = "ACCEPT_CONTRIBUTE_REQUEST_FAIL";
export const IGNORE_CONTRIBUTE_REQUEST = "IGNORE_CONTRIBUTE_REQUEST";
export const IGNORE_CONTRIBUTE_REQUEST_SUCCESS =
  "IGNORE_CONTRIBUTE_REQUEST_SUCCESS";
export const IGNORE_CONTRIBUTE_REQUEST_FAIL = "IGNORE_CONTRIBUTE_REQUEST_FAIL";

// Contribute room
export const FETCH_CONTRIBUTE_ROOM = "FETCH_CONTRIBUTE_ROOM";
export const FETCH_CONTRIBUTE_ROOM_SUCCESS = "FETCH_CONTRIBUTE_ROOM_SUCCESS";
export const FETCH_CONTRIBUTE_ROOM_FAIL = "FETCH_CONTRIBUTE_ROOM_FAIL";
export const RESET_CONTRIBUTE_ROOM = "RESET_CONTRIBUTE_ROOM";
export const STOP_COLLABORATING = "STOP_COLLABORATING";
export const STOP_COLLABORATING_SUCCESS = "STOP_COLLABORATING_SUCCESS";
export const STOP_COLLABORATING_FAIL = "STOP_COLLABORATING_FAIL";
export const UPDATE_SOLUTION = "UPDATE_SOLUTION";
export const UPDATE_SOLUTION_SUCCESS = "UPDATE_SOLUTION_SUCCESS";
export const UPDATE_SOLUTION_FAIL = "UPDATE_SOLUTION_FAIL";
export const UPDATE_MEMBER_REVIEW = "UPDATE_MEMBER_REVIEW";
export const UPDATE_MEMBER_REVIEW_SUCCESS = "UPDATE_MEMBER_REVIEW_SUCCESS";
export const UPDATE_MEMBER_REVIEW_FAIL = "UPDATE_MEMBER_REVIEW_FAIL";
export const FINALIZE_POST = "FINALIZE_POST";
export const FINALIZE_POST_SUCCESS = "FINALIZE_POST_SUCCESS";
export const FINALIZE_POST_FAIL = "FINALIZE_POST_FAIL";
export const UPDATE_KARMA_WINNER = "UPDATE_KARMA_WINNER";
export const UPDATE_KARMA_WINNER_SUCCESS = "UPDATE_KARMA_WINNER_SUCCESS";
export const UPDATE_KARMA_WINNER_FAIL = "UPDATE_KARMA_WINNER_FAIL";

// Contribute room messages
export const FETCH_ROOM_MESSAGES = "FETCH_ROOM_MESSAGES";
export const FETCH_ROOM_MESSAGES_SUCCESS = "FETCH_ROOM_MESSAGES_SUCCESS";
export const FETCH_ROOM_MESSAGES_FAIL = "FETCH_ROOM_MESSAGES_FAIL";
export const FETCH_ROOM_MESSAGE = "FETCH_ROOM_MESSAGE";
export const FETCH_ROOM_MESSAGE_SUCCESS = "FETCH_ROOM_MESSAGE_SUCCESS";
export const FETCH_ROOM_MESSAGE_FAIL = "FETCH_ROOM_MESSAGE_FAIL";
export const ADD_ROOM_MESSAGE = "ADD_ROOM_MESSAGE";
export const FETCH_MORE_ROOM_MESSAGES = "FETCH_MORE_ROOM_MESSAGES";
export const FETCH_MORE_ROOM_MESSAGES_SUCCESS =
  "FETCH_MORE_ROOM_MESSAGES_SUCCESS";
export const FETCH_MORE_ROOM_MESSAGES_FAIL = "FETCH_MORE_ROOM_MESSAGES_FAIL";
export const RESET_ROOM_MESSAGES = "RESET_ROOM_MESSAGES";

// Contribute room shared notes
export const UPDATE_SHARED_NOTES = "UPDATE_SHARED_NOTES";

// Contribute room kanban
export const ADD_CARD = "ADD_CARD";
export const ADD_LIST = "ADD_LIST";
export const DRAG_HAPPENED = "DRAG_HAPPENED";
export const UPDATE_LIST = "UPDATE_LIST";
export const UPDATE_CARD = "UPDATE_CARD";
export const DELETE_LIST = "DELETE_LIST";
export const DELETE_CARD = "DELETE_CARD";

// Communitites
export const FETCH_COMMUNITIES = "FETCH_COMMUNITIES";
export const FETCH_COMMUNITIES_SUCCESS = "FETCH_COMMUNITIES_SUCCESS";
export const FETCH_COMMUNITIES_FAIL = "FETCH_COMMUNITIES_FAIL";

// Reviews
export const FETCH_REVIEWS = "FETCH_REVIEWS";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAIL = "FETCH_REVIEWS_FAIL";
export const FETCH_MORE_REVIEWS = "FETCH_MORE_REVIEWS";
export const FETCH_MORE_REVIEWS_SUCCESS = "FETCH_MORE_REVIEWS_SUCCESS";
export const FETCH_MORE_REVIEWS_FAIL = "FETCH_MORE_REVIEWS_FAIL";

// Donation options
export const FETCH_DONATION_OPTIONS = "FETCH_DONATION_OPTIONS";
export const FETCH_DONATION_OPTIONS_SUCCESS = "FETCH_DONATION_OPTIONS_SUCCESS";
export const FETCH_DONATION_OPTIONS_FAIL = "FETCH_DONATION_OPTIONS_FAIL";

// Folders
export const FOLDERS_FETCH = "FOLDERS_FETCH";
export const FOLDERS_SUCCESS = "FOLDERS_SUCCESS";
export const FOLDERS_FAIL = "FOLDERS_FAIL";
export const EDIT_FOLDER = "EDIT_FOLDER";
export const EDIT_FOLDER_SUCCESS = "EDIT_FOLDER_SUCCESS";
export const EDIT_FOLDER_FAIL = "EDIT_FOLDER_FAIL";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const CREATE_FOLDER_FAIL = "CREATE_FOLDER_FAIL";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";
export const DELETE_FOLDER_FAIL = "DELETE_FOLDER_FAIL";
export const SET_CURRENT_FOLDER = "SET_CURRENT_FOLDER";
export const REMOVE_CURRENT_FOLDER = "REMOVE_CURRENT_FOLDER";

// Files
export const FILES_FETCH = "FILES_FETCH";
export const FILES_SUCCESS = "FILES_SUCCESS";
export const FILES_FAIL = "FILES_FAIL";
export const EDIT_FILE = "EDIT_FILE";
export const EDIT_FILE_SUCCESS = "EDIT_FILE_SUCCESS";
export const EDIT_FILE_FAIL = "EDIT_FILE_FAIL";
export const CREATE_FILE = "CREATE_FILE";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const CREATE_FILE_FAIL = "CREATE_FILE_FAIL";
export const DELETE_FILE = "DELETE_FILE";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAIL = "DELETE_FILE_FAIL";

// FoldersMove
export const MOVE_FOLDERS_FETCH = "MOVE_FOLDERS_FETCH";
export const MOVE_FOLDERS_SUCCESS = "MOVE_FOLDERS_SUCCESS";
export const MOVE_FOLDERS_FAIL = "MOVE_FOLDERS_FAIL";
export const SET_CURRENT_MOVE_FOLDER = "SET_CURRENT_MOVE_FOLDER";
export const REMOVE_CURRENT_MOVE_FOLDER = "REMOVE_CURRENT_MOVE_FOLDER";

// Folder Move
export const MOVE_FOLDER = "MOVE_FOLDER";
export const MOVE_FOLDER_SUCCESS = "MOVE_FOLDER_SUCCESS";
export const MOVE_FOLDER_FAIL = "MOVE_FOLDER_FAIL";

// File Move
export const MOVE_FILE = "MOVE_FILE";
export const MOVE_FILE_SUCCESS = "MOVE_FILE_SUCCESS";
export const MOVE_FILE_FAIL = "MOVE_FILE_FAIL";
